Update azure-functions-app-java.yml

diff --git a/.github/workflows/azure-functions-app-java.yml b/.github/workflows/azure-functions-app-java.yml
--- a/.github/workflows/azure-functions-app-java.yml
+++ b/.github/workflows/azure-functions-app-java.yml
@@ -22,10 +22,18 @@ jobs:
       - name: Download JavaFX SDK and MSSQL driver
         run: |
           mkdir -p dependencies/javafx-sdk dependencies/sqljdbc
+          # Download JavaFX SDK
           curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_linux-x64_bin-sdk.zip
           unzip javafx-sdk.zip -d dependencies/javafx-sdk
+          # Download MSSQL driver
+          rm -f sqljdbc.zip
           curl -L -o sqljdbc.zip https://go.microsoft.com/fwlink/?linkid=2154486
+          if ! unzip -tqq sqljdbc.zip; then
+            echo "Downloaded SQLJDBC file is invalid."
+            exit 1
+          fi
           unzip sqljdbc.zip -d dependencies/sqljdbc
+
 
       - name: Build JavaFX app
         run: |
